name: "Build and run tests"
on:
  pull_request:
    branches: ["master", "develop"]

jobs:
  build_and_test:
    runs-on: macOS-latest

    timeout-minutes: 60

    env:
      XC_VERSION: ${{ '14.1' }}

    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - name: "Install system dependencies"
        run: |
          gem install bundler
          bundle install
        working-directory: Jokes

      - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
      - name: "Install CocoaPods dependencies"
        run: |
          gem install cocoapods
          pod install
        working-directory: Jokes

      - name: "Run tests"
        run: "bundle exec fastlane tests"
        working-directory: Jokes
