name: "Build and run tests"
on:
  pull_request:
    branches: ["master", "develop"]

jobs:
  build_and_test:
    runs-on: macOS-latest

    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: "Install system dependencies"
        run: |
          gem install bundler
          bundle install
        working-directory: Jokes

      - name: "Install CocoaPods dependencies"
        run: |
          gem install cocoapods
          pod install
        working-directory: Jokes

      - name: "Create LocalDevelopment.xcconfig file"
        run: "echo 'APP_BUNDLE_ID = id\nAPP_NAME = name\nTASK_CONFIGURATOR_ENVIRONMENT = memory\nOPERATION_LOGGING_ENABLED = false\nJOKES_ENDPOINT = url' > LocalDevelopment.xcconfig"
      working-directory: Jokes/Configurations/Development

      - name: "Create LocalProduction.xcconfig file"
        run: "echo 'APP_BUNDLE_ID = id\nAPP_NAME = name\nTASK_CONFIGURATOR_ENVIRONMENT = memory\nOPERATION_LOGGING_ENABLED = false\nJOKES_ENDPOINT = url' > LocalProduction.xcconfig"
        working-directory: Jokes/Configurations/Production

      - name: "Run tests"
        run: "bundle exec fastlane tests"
        working-directory: Jokes
