# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'Jokes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jokes
  pod "Kingfisher"

  target 'JokesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JokesUITests' do
    # Pods for testing
  end

end
